"""Tool path-to-name mapping for all 96 ClearerThinking tools."""

TOOLS_MAP: dict[str, str] = {
    "/unique-traits-test/": "Unique Traits Test",
    "/understanding-your-morality": "Understand Your Morality",
    "/imposter_syndrome.html": "The Imposter Syndrome Test",
    "/social_biases.html": "How Other People Can Make You Irrational",
    "/flexible_thinking.html": "Flexible Thinking",
    "/predict_correlations.html": "Predict Psychological Correlations",
    "/productive_disagreement.html": "Productive Disagreements",
    "/retrocaster.html": "Retrocaster",
    "/faulty_reasoning_quiz.html": "Faulty Reasoning Quiz",
    "/biosafety_quiz.html": "Biosafety Quiz",
    "/make_your_work_more_joyful.html": "Make Your Work More Joyful",
    "/kind_and_effective_communication.html": "Kind and Effective Communication",
    "/effective_trust_repair.html": "Effective Trust Repair",
    "/emotional_obstacles_to_doing_good.html": "Emotional Obstacles to Doing Good",
    "/worlds_biggest_problems_quiz.html": "World's Biggest Problems Quiz",
    "/political_bias_test.html": "Political Bias Test",
    "/question_your_identity.html": "Question Your Identity",
    "/EARR_framework.html": "Resolve Harmful Situations",
    "/savoring.html": "Savor Your Life",
    "/skeptical_seekers.html": "Are You a Skeptic or a Seeker?",
    "/tactics_for_happier_living.html": "Tactics for Happier Living",
    "/common_misconceptions.html": "The Common Misconceptions Test",
    "/decisionmaker.html": "The Decision Advisor",
    "/hidden_meaning_of_sounds.html": "The Hidden Meaning of Sounds",
    "/planning_fallacy.html": "The Planning Fallacy",
    "/relationship_review.html": "The Relationship Review",
    "/understanding_bayes_theorem.html": "Understanding Bayes Theorem",
    "/what_causes_match_your_values.html": "What Causes Match Your Values?",
    "/what_to_know_about_suicide.html": "What to Know About Suicide",
    "/when_to_stop_exploring.html": "When To Stop Exploring",
    "/your_primal_world_beliefs.html": "Your Primal World Beliefs",
    "/spark_the_mood_you_want.html": "Spark the Mood You Want",
    "/achieve_your_goals.html": "Achieve Your Goals",
    "/boost_your_productivity.html": "Boost Your Productivity",
    "/career_fulfillment_diagnostic.html": "Career Fulfillment Diagnostic",
    "/can_you_guess_which_charities_work.html": "Charity Effectiveness",
    "/daily_ritual.html": "Daily Ritual: A Habit Creation System",
    "/design_your_own_self_experiment.html": "Design Your Own Self-Experiment",
    "/explanation_freeze.html": "Explanation Freeze",
    "/gender_continuum_test.html": "Gender Continuum Test",
    "/how_rational_are_you_really_take_the_test.html": "How Rational Are You, Really?",
    "/is_your_memory_like_a_photograph.html": "Is Your Memory Like A Photograph?",
    "/mistakes.html": "Learning From Mistakes",
    "/lcq.html": "Life Changing Questions",
    "/managing_arguments.html": "Managing Arguments in Relationships",
    "/moodboosters.html": "Mood Boosters",
    "/Cognitive_Defusion": "Step Back From Your Thoughts",
    "/how-to-compliment.html": "Craft Perfect Compliments",
    "/cognitive-test-intro.html": "Cognitive Assessment",
    "/cult_assessment.html": "The Cult Assessment",
    "/astrology_challenge.html": "The Astrology Challenge",
    "/create_your_custom_clearer_thinking_plan.html": "Clearer Thinking Paths",
    "/personality.html": "The Ultimate Personality Test",
    "/nuanced_thinking_techniques.html": "Nuanced Thinking Techniques",
    "/pathkeeper_intro.html": "Pathkeeper",
    "/practice_self-compassion.html": "Practice Self-Compassion",
    "/art_of_collaboration.html": "The Art of Collaboration",
    "/long-term_future_quiz.html": "Long-Term Future Quiz",
    "/artificial_intelligence_quiz.html": "Artificial Intelligence Quiz",
    "/your_quarterly_life_review.html": "Your Quarterly Life Review",
    "/uncover_your_guiding_principles.html": "Uncover Your Guiding Principles",
    "/program_yourself.html": "Program Yourself to Improve Your Life",
    "/reframing_negative_emotions.html": "Reframing Negative Emotions",
    "/rhetorical_fallacies.html": "Rhetorical Fallacies",
    "/seek_criticism_tool.html": "Seeking Outside Criticism",
    "/surpass_self-limiting-beliefs.html": "Surpass Self-Limiting Beliefs",
    "/challenge_your_deepest_beliefs.html": "The Belief Challenger",
    "/confrontation_aid.html": "The Confrontation Aid",
    "/would_you_make_a_good_tech_startup_founder.html": "The Entrepreneur Test",
    "/intrinsic_values_test.html": "The Intrinsic Values Test",
    "/question_of_evidence.html": "The Question of Evidence",
    "/sunk_costs.html": "The Sunk Cost Fallacy",
    "/what_is_your_time_really_worth_to_you.html": "Value Of Your Time Calculator",
    "/goal_trainer_ct.html": "What Makes an Effective Goal?",
    "/should_you_trust_your_thinking.html": "When Are You Overconfident?",
    "/sources_of_pleasure.html": "Your Greatest Sources of Pleasure",
    "/replace_unhelpful_coping_strategies.html": "Replace Unhelpful Coping Strategies",
    "/40_winks.html": "40 Winks: Better Sleep Made Easy",
    "/become_a_great_listener.html": "Become A Great Listener",
    "/building_happiness_habits.html": "Building Happiness Habits",
    "/can_you_detect_weak_arguments.html": "Can You Detect Weak Arguments?",
    "/change_behavior.html": "Change Behavior for the Better",
    "/credentialist_test.html": "Credentialist Test",
    "/defining_emotions.html": "Defining Emotions",
    "/enhancing_creativity.html": "Enhancing Creativity",
    "/fail-safing_your_plans.html": "Fail-Safing Your Plans",
    "/overcome_procrastination.html": "Get Going: Overcome Procrastination",
    "/how_well_anchored_are_your_estimates.html": "How Airtight Are Your Estimates?",
    "/improve_your_frequency_predictions.html": "Improve Your Frequency Predictions",
    "/philosophical_beliefs.html": "Learn Your Philosophical Beliefs",
    "/how_to_do_more_good.html": "Leaving Your Mark on the World",
    "/life_assessment.html": "Lifetime Aspirations",
    "/introduction.html": "Mental Traps",
    "/overconfidence_analyzer.html": "Overconfidence Analyzer",
    "/personality-test.html": "Personality Test",
    "/advanced-cognitive-assessment": "Advanced Cognitive Assessment",
}

# Reverse lookup: tool name → page path
TOOLS_NAME_TO_PATH: dict[str, str] = {v: k for k, v in TOOLS_MAP.items()}

# All known tool paths as a set for fast lookup
KNOWN_TOOL_PATHS: set[str] = set(TOOLS_MAP.keys())
